### ISSUE TITLE
%matplotlib inline statement Not working.

### ISSUE THREAD

**Issue by neleyej** [fazeelkhalid/artificial-intelligence-lab#1]
Please check it https://github.com/fazeelkhalid/artificial-intelligence-lab/blob/main/Lab10/lab10%20_%20Sol.py#L23
%matplotlib inline statement in line number 23 is not working. Getting error at the time of execution.

**Comment by fazeelkhalid** [comment]
Yeah, you are right you just need to remove that line if you are using spider.
